spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:  #객체지향 모델을 관계형 DB로 연결해주는 framework
      ddl-auto: create #drop and 추가  update 변경시 서버종료되도 data저장
    properties:
     hibernate:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
